#默认使用配置

server:
  port: 8081
#公共配置与profiles选择无关
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  typeAliasesPackage: com.gnq.giant.*.entities
  mapperLocations: classpath:mybatis/mapper/*.xml
logging:
  config: classpath:log4j.xml

---

#开发配置
spring:
#  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giant
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
#    timeout: 0