#默认使用配置

server:
  port: 8081
#公共配置与profiles选择无关
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  typeAliasesPackage: com.gnq.giant.*.entities
  mapperLocations: classpath:mybatis/mapper/*.xml
logging:
  config: classpath:log4j.xml
---

#开发配置
spring:
#  profiles: dev
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: microservicecloud-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giant?allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    timeout:  3000
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#neo4j图数据库连接
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
#  swagger:
#    enabled: true
#    base-package: com.gnq.giant.system.controller
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
#    timeout: 0